### ISSUE TITLE
Unable to build the source code

### ISSUE THREAD

**Issue by StevenRasmussen** [delegateas/XrmDefinitelyTyped#263]
I have followed the directions on the `ReadMe` but have been unable to successfully build the source code.  It appears that it could be an issue with Fake (which appears to be deprecated).  It seems like it's trying to hit a URL that no longer exists [https://artifactory.palantir.build/artifactory/api/npm/all-npm/parse-node-version/-/parse-node-version-1.0.1.tgz](https://artifactory.palantir.build/artifactory/api/npm/all-npm/parse-node-version/-/parse-node-version-1.0.1.tgz).  Here is the output after trying to run the `build.exe` command from the root directory:

```
This runner is now obsolete with FAKE 5, please upgrade to the new .Net Core runner. See https://fake.build/fake-migrate-to-fake-5.html
To remove this warning you can append the '--removeLegacyFakeWarning' argument or set the 'FAKE_NO_LEGACY_WARNING' environment variable to 'true'
run Build
Building project with version: LocalBuild
Shortened DependencyGraph for Target Build:
<== Build
   <== AssemblyInfo
      <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - AssemblyInfo
Group - 3
  - Build
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0072793
Starting target 'AssemblyInfo'
Finished (Success) 'AssemblyInfo' in 00:00:00.0161013
Starting target 'Build'
Starting task 'DotNet:build': C:\Temp\XrmDefinitelyTyped\XrmDefinitelyTyped.sln
C:\Temp\XrmDefinitelyTyped> "C:\Program Files\dotnet\dotnet.EXE" build "C:\Temp\XrmDefinitelyTyped\XrmDefinitelyTyped.sln" --configuration Release /nodeReuse:False /nowarn:NU5100 /p:Version=6.1.0 "/p:ReleaseNotes=Add support for AppSidePane - https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-app-appsidepane (%40mathiasbl)
Typings for currentView on the view Selector (%40skovlund%2C %40mkholt)" (In: false, Out: false, Err: false)
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  npm WARN old lockfile
  npm WARN old lockfile The package-lock.json file was created with an old version of npm,
  npm WARN old lockfile so supplemental metadata must be fetched from the registry.
  npm WARN old lockfile
  npm WARN old lockfile This is a one-time fix-up, please be patient...
  npm WARN old lockfile
  npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
  npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
  npm WARN deprecated is-buffer@1.1.5: This version of 'is-buffer' is out-of-date. You must update to v1.1.6 or newer
  npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
  npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
  npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
  npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
  npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
  npm ERR! code ENOTFOUND
  npm ERR! syscall getaddrinfo
  npm ERR! errno ENOTFOUND
  npm ERR! network request to https://artifactory.palantir.build/artifactory/api/npm/all-npm/parse-node-version/-/parse-node-version-1.0.1.tgz failed, reason: getaddrinfo ENOTFOUND artifactory.palantir.build
  npm ERR! network This is a problem related to network connectivity.
  npm ERR! network In most cases you are behind a proxy or have bad network settings.
  npm ERR! network
  npm ERR! network If you are behind a proxy, please make sure that the
  npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

  npm ERR! A complete log of this run can be found in:
  npm ERR!     C:\Users\SteveRasmussen\AppData\Local\npm-cache\_logs\2022-03-15T21_19_13_338Z-debug-0.log
C:\Temp\XrmDefinitelyTyped\src\XrmDefinitelyTyped\XrmDefinitelyTyped.fsproj(137,5): error MSB3073: The command "npm install" exited with code 1.

Build FAILED.

C:\Temp\XrmDefinitelyTyped\src\XrmDefinitelyTyped\XrmDefinitelyTyped.fsproj(137,5): error MSB3073: The command "npm install" exited with code 1.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:01:19.32
Finished (Failed) 'DotNet:build' in 00:01:19.9243979
Finished (Failed) 'Build' in 00:01:19.9350952

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0028928
AssemblyInfo   00:00:00.0158691
Build          00:01:19.9345408   (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
Total:         00:01:20.0742937
Status:        Failure
---------------------------------------------------------------------
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Fake.Core.BuildFailedException: Target 'Build' failed. ---> System.AggregateException: One or more errors occurred. ---> Fake.DotNet.MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.
   at Fake.DotNet.MSBuild.handleAfterRun[a](String command, a binLogPath, Int32 exitCode, String project) in d:\a\1\s\src\app\Fake.DotNet.MSBuild\MSBuild.fs:line 756
   at Fake.DotNet.DotNet.execWithBinLog(String project, Options common, String command, String args, CliArguments msBuildArgs) in d:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 985
   at Fake.DotNet.DotNet.build(FSharpFunc`2 setParams, String project) in d:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 1397
   at FSI_0005.Build.clo@131-4.Invoke(TargetParameter _arg3)
   at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in d:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 300
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context) in d:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 968
   at Fake.Core.TargetModule.runOrDefault(String defaultTarget) in d:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 1150
   at <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Fake.FSIHelper.runScriptCached@360.Invoke(Unit unitVar0) in d:\a\1\s\src\legacy\FakeLib\FSIHelper.fs:line 368
Fake.Core.BuildFailedException: Target 'Build' failed. ---> System.AggregateException: One or more errors occurred. ---> Fake.DotNet.MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.
   at Fake.DotNet.MSBuild.handleAfterRun[a](String command, a binLogPath, Int32 exitCode, String project) in d:\a\1\s\src\app\Fake.DotNet.MSBuild\MSBuild.fs:line 756
   at Fake.DotNet.DotNet.execWithBinLog(String project, Options common, String command, String args, CliArguments msBuildArgs) in d:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 985
   at Fake.DotNet.DotNet.build(FSharpFunc`2 setParams, String project) in d:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 1397
   at FSI_0005.Build.clo@131-4.Invoke(TargetParameter _arg3) in C:\Temp\XrmDefinitelyTyped\build.fsx:line 132
   at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in d:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 300
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context) in d:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 968
   at Fake.Core.TargetModule.runOrDefault(String defaultTarget) in d:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 1150
   at <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@() in C:\Temp\XrmDefinitelyTyped\build.fsx:line 245
Stopped due to error
```

**Comment by misoeli** [comment]
I'm able to reproduce, but only on a new machine. Looking in to it.

**Comment by misoeli** [comment]
The branch [here](https://github.com/delegateas/XrmDefinitelyTyped/tree/263_eslint) should be buildable for you now. I updated tslint, but apparently, there's quite a few linter issues left. I would prefer to look into those before merging into main. I hope to have time to look into that tomorrow.

**Comment by misoeli** [comment]
tslint has now been replaced with eslint - main should work as well.
